### ISSUE TITLE
Placing orders through the api?

### ISSUE THREAD

**Issue by kdvolder** [qtrade-exchange/qtrade-docs#20]
Is it possible? (I am assuming it mus be be possible somehow, since the web-based trading platform allows me to place orders).

However, can't seem to find info about it in the api docs.

**Comment by Henelik** [comment]
Yes, it is possible.  The endpoints for placing orders are listed as "[Create Sell Limit](https://qtrade-exchange.github.io/qtrade-docs/#create-sell-limit)" and "[Create Buy Limit](https://qtrade-exchange.github.io/qtrade-docs/#create-buy-limit)" under the Private endpoints section in the docs.

**Comment by kdvolder** [comment]
I saw that but somehow got the impression its not for placing trade orders for stock but only for currency exchange?

It's starting to dawn on me that perhaps I'm just confused what this whole api is for. Is this an api for interfacing with the qtrade online trading platform? I.e. https://www.qtrade.ca/en/investor/trading/platform.html
